### PR TITLE
Added threadsafe when trying to read/write dictionary value MTDB-12708

### PR DESCRIPTION
**Pull request by dinhnhat0401**
In notion

### CODE REVIEW

**Comment by jenbitcoin** [comment]
I think the ThreadSafeCache is a bit unclear.. since this is related to dictionary, maybe we can rename to ThreadSafeDictionary? @dinhnhat0401

**Comment by dinhnhat0401** [comment]
@jenbitcoin changed with this commit https://github.com/bitcoin-portal/asset-converter/pull/28/commits/0dfe49accb5a25e8d642d61696099c7dac1dc9ef
thanks.

**Review by jenbitcoin — APPROVED** [review]
lgtm, pls check with @jkatayama  about putting this in the assetConverter library.
thanks!

**Review by jkatayama — APPROVED** [review]
confirmed test failed without ThreadSafeDictionary

**Pull request merged**
